name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # O site atualizará sempre que você der push na main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Install pnpm 📦
        uses: pnpm/action-setup@v4
        with:
          version: 10 # Alinhado com a versão que você usa

      - name: Setup Node 🏗️
        uses: actions/setup-node@v4
        with:
          node-cache: 'pnpm'

      - name: Install and Build 🚀
        run: |
          pnpm install
          pnpm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # Pasta que o seu Vite gera na raiz
          branch: gh-pages
